IF
	Global("LaeralSpawned","GLOBAL",0)
	Global("LaeralUmarHills","GLOBAL",1)
	Global("DXNameChange2","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("DXNameChange2","GLOBAL",1)
		ActionOverride("dx#laera",SetName(@998))
		Continue()
END

IF
	Global("Cauldron2","DX#001",1)
	!Global("LaeralUmarHills","GLOBAL",1)
	!Global("LaeralAttacked","GLOBAL",1)
THEN
	RESPONSE #100
		CreateCreatureDoor("dx#laera",[1027.358],S)
		SetGlobal("LaeralUmarHills","GLOBAL",1)
		Continue()
END
