IF
	Entered([PC])
	Global("EnteredAR0907","GLOBAL",1)
	!Global("ACH_TWISTED_VICTORY","GLOBAL",1)
	Global("MurdersSolved","GLOBAL",1)
	Global("TwistedAmbush","GLOBAL",0)
THEN
	RESPONSE #100
		CreateCreature("dx#taw01",[1633.1202],NW)  // Rune Mage
		CreateCreature("TANTHF01",[1695.1190],NW)  // Rune Assassin
		CreateCreature("TANTHF01",[1613.1289],NW)  // Rune Assassin
		SetGlobal("TwistedAmbush","GLOBAL",1)
END