IF
	GlobalTimerExpired("zalladlg","LOCALS")
	!Global("zallaout1","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("zallaout1","LOCALS",1)
		StartDialogueNoSet(LastSeenBy(Myself))
END

IF
	HPLT(Myself,40)
	!Global("TSFired","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("TSFired","LOCALS",1)
		SetGlobal("CowledWarning","GLOBAL",7)
		ReallyForceSpell(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)
		SetGlobalTimer("zalladlg","LOCALS",2)
		Wait(2)
END